language: node_js
node_js:
  - "8"

cache: yarn

after_success: 
  - echo "Bundling with webpack ..."
  - npm run build

deploy:
  provider: npm
  email: opensource@dm.de
  api_key:
    secure: Fe36+bh131ox/GWO55LAIyutYRBebzkYte5is8aT9x5vsFz8TijI8SMtlMR0bFrVbYgxp7WlI65i7jkyiepZ0ExWF4B79HJ8Sf7oftDfz4ZKo2wZbUsn/qZbM5Wh6VozTl59limp0f0ePxQ91qJ/bYlZWVcFjm3bsgxUjezZEPZIVnl96tOUWCTIU1nRJuVroNnweTqfzeiQryDKRggUMaXLO+yqm4l84H7f6IrKpNasCBxwDQCnyOOBalHFxpZbxl98NOia+inbZC6rpmzYZEn51YocZ5jAesq+xjl11J6lRFzbx3EP5LKOlUiEBf6EjDQGtoAq1Wv8H5/fx21RjbLmetE4p+nT1rWVfuTj38pti2QrxPiMrsaqrKC8cKpD712RTEJyQ51fzu+VQLySRTyG0TkXXntvKEgejkDezzcFAjUjPk2BK+oUFhmuJFRdtzA1J5RknWcfbj2/jiUwxHsQzaUj45jcxYUBQRo1Wr0gKI3x6FKpndfXMYZuno6Ky/ONPSKCnfaz9vnGkRolH1r6QKTJ+ObIYsHkImkhejz2rO2/+Urtpf92CIL1Vz0n/f1V9Tg8AidGVbECFnVCDT3linX22w4Vv0MVeR9POoB8E6tttMrHJuIOFRF7/q1w4GD2lKl1ooauDwibSluCkon6DPtsVrCT93BSlhqEvYo=
  on:
    tags: true
    repo: dm-drogeriemarkt/material-scrollable-time-picker
